spring:
  application.name: diverse
  datasource:
    url: jdbc:mariadb://${DATASOURCE_URL}/${DATASOURCE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://${MONGODB_URL}/${MONGODB_NAME}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  mvc:
    static-path-pattern: /static/**

server:
  shutdown: graceful

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 86400000
    refresh-token-expiration: 172800000
    issuer: ${JWT_ISSUER}

