spring:
  application.name: diverse
  datasource:
    url: jdbc:mariadb://${DATASOURCE_HOST}:${DATABASE_PORT}/${DATASOURCE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  shutdown: graceful

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 86400000
    refresh-token-expiration: 172800000
    issuer: pplus
